# Generated by Django 4.1.1 on 2022-09-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('material', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
